### PR TITLE
Updated Facebook typings and added example

### PR DESCRIPTION
**Pull request by jtmthf**
I had to create a Facebook app for this example to work. If you want to send me either your fbid or username I will add you as an owner to Facebook application.

### CODE REVIEW

**Comment by janaagaard75** [comment]
The first contribution! \o/ How do you celebrate something like that? 🎉

**Comment by janaagaard75** [comment]
My Facebook profile can be accessed at https://www.facebook.com/janaagaard, so I guess that makes my username `janaagaard`.

**Comment by jtmthf** [comment]
Done 👍

**Comment by janaagaard75** [comment]
I took the liberty to make a couple of minor syntax changes to the code. Is that... Okay? I believe in the value of using the same syntax throughout the code, but I would alsolove to build a community to help completing and keeping these type definitions up to date, and I guess these kind of changes could turn some developers aways. What do you think?

**Comment by jtmthf** [comment]
Yeah go ahead with any changes you want. Personally I find the duplicate import syntax a bit harder to read, but it works. It might be worth using prettier for formatting so that there's no need for discussions on styling with future contributors.

**Comment by janaagaard75** [comment]
The main reason I use one import per line is that it is my experience that the conventional syntax is very prone to cause merge conflicts. With a single import per line and everybody sorting the imports alphabetically, these conflicts should be much less frequent.

I haven't thought about the readability of the imports, though. And now that I think about it, I think it's very rare that I look at the imports for a file. It would mostly be checking if there are a lot of them, because that would be a sign that the class has too many responsibilities.

**Comment by jtmthf** [comment]
That's true on both merge-conflicts and not really looking at the imports. The big issue with enforcement will be the lack of an existing TSLint rule for multi-import in that style. I suppose another minor issue would not being able to use automatic imports, but I don't think too many people use that feature yet.

**Pull request merged**
