### PR TITLE
Update expo.d.ts

### PR DESCRIPTION
**Pull request by PavelPZ**
Just single character :-)
Thanks

### CODE REVIEW

**Comment by PavelPZ** [comment]
Just another change: 

```function registerRootComponent<P, S>(component: React.ComponentType<P>): React.Component<P, S>```

**Comment by janaagaard75** [comment]
This signature is more correct, no? See <https://github.com/expo/expo-sdk/blob/master/src/launch/registerRootComponent.js>.

```typescript
function registerRootComponent<P>(component: React.ComponentType<P>): void
```

**Comment by janaagaard75** [comment]
I accidentally already merged in the second option - I wanted to create a branch for it, but messed it somehow. So let me know if this works in your app.

**Comment by PavelPZ** [comment]
Yes, you are true, ```function registerRootComponent(component: React.ComponentType<any>): void``` is the best option.

**Comment by janaagaard75** [comment]
Great. Thanks for the feedback.

**Pull request merged**
